all:
	(cd network_load && $(MAKE)) >/dev/null
	(cd location && $(MAKE)) >/dev/null
	(cd space_scan && $(MAKE)) >/dev/null
	(cd now_playing && $(MAKE)) >/dev/null
	(cd system_stats && $(MAKE)) >/dev/null
	(cd menus && $(MAKE)) >/dev/null
